[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
swaps = "8wJ5YqtKrjH71ZKnSVeVtU8wQRJYAT7e6TrX2kUu1KLY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
