name: Multisig CI

on:
  push:
    branches: [ "programs/multisig" ]
  pull_request:
    branches: [ "programs/multisig" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: npm install

      - name: Install Solana CLI v1.18.18
        run: |
         sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
         echo 'export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"' >> ~/.bashrc
         source ~/.bashrc
      - uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: '0.30.1'

      - name: Generate new keypair
        run: | 
          solana-keygen new --no-bip39-passphrase
          solana address
          solana balance
        shell: bash

      - name: Set solana target cluster to local
        run: solana config set --url http://localhost:8899
        shell: bash

      - name: Check solana config
        run: solana config get
        shell: bash

      - run: npm run anchor build
        shell: bash

      - run: npm run anchor test
        shell: bash
